### ISSUE TITLE
Failed to load the busy-signal package

### ISSUE THREAD

**Issue by enosis-sameen** [steelbrain/busy-signal#23]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Ultimate 
**Thrown From**: [busy-signal](https://github.com/steelbrain/busy-signal) package 1.4.0

### Stack Trace

Failed to load the busy-signal package

```
At UNKNOWN: unknown error, open 'C:\Users\saifullah\.atom\compile-cache\js\babel\ce35514db6341e7f32f611892410fdea5abbc019\569ef8d176a848e802cf6b0fd306bff6542718c8.js'

Error: UNKNOWN: unknown error, open 'C:\Users\saifullah\.atom\compile-cache\js\babel\ce35514db6341e7f32f611892410fdea5abbc019\569ef8d176a848e802cf6b0fd306bff6542718c8.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.writeFileSync (fs.js:1343:33)
    at Object.writeFileSync (/app.asar/node_modules/fs-plus/lib/fs-plus.js:288:17)
    at writeCachedJavascript (/app.asar/src/compile-cache.js:111:6)
    at compileFileAtPath (/app.asar/src/compile-cache.js:92:7)
    at /app.asar/src/compile-cache.js:215:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/busy-signal/lib/index.js:3:13)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/app.asar/src/package-manager.js:407:19)
    at /app.asar/src/atom-environment.js:792:28
```

### Commands

```
```

### Non-Core Packages

```
atom-typescript 11.0.3 
autocomplete-json 5.4.0 
autocomplete-modules 1.6.9 
busy-signal 1.4.0 
intentions 1.1.2 
linter 2.1.4 
linter-ui-default 1.2.3 
platformio-ide-terminal 2.5.0 
```

**Comment by steelbrain** [comment]
Atom internal error, either restart or uninstall/reinstall of this package should fix

**Comment by andrewkhardy** [comment]
uninstall/reinstall does not work. Please reopen
