### ISSUE TITLE
Uncaught Error: Status 'sbt yankeevoucher: starting sbt' is already set

### ISSUE THREAD

**Issue by cruzlauroiii** [steelbrain/busy-signal#34]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [busy-signal](https://github.com/steelbrain/busy-signal) package 1.4.3

### Stack Trace

Uncaught Error: Status 'sbt yankeevoucher: starting sbt' is already set

```
At /Users/stellar/.atom/packages/busy-signal/lib/registry.js:50

Error: Status 'sbt yankeevoucher: starting sbt' is already set
    at Registry.statusAdd (/packages/busy-signal/lib/registry.js:50:13)
    at /packages/busy-signal/lib/registry.js:31:12
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Provider.add (/packages/busy-signal/lib/provider.js:21:18)
    at Project.module.exports.Project.startTerm (/packages/sbt/lib/project.coffee:49:19)
    at /packages/sbt/lib/project.coffee:91:12
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
     -9:13.3.0 core:save (input.hidden-input)
     -7:38.5.0 editor:newline (input.hidden-input)
     -7:37.1.0 core:paste (input.hidden-input)
     -7:33.6.0 intentions:highlight (input.hidden-input)
     -7:31.9.0 core:save (input.hidden-input)
  2x -7:07.9.0 core:backspace (input.hidden-input)
     -7:06.1.0 core:save (input.hidden-input)
     -6:04.3.0 tree-view:move (span.name.icon.icon-file-text)
     -6:03.2.0 core:select-all (input.hidden-input)
  8x -6:01.8.0 core:backspace (input.hidden-input)
     -5:56.4.0 core:confirm (input.hidden-input)
     -4:58.3.0 core:copy (input.hidden-input)
  2x -4:04.3.0 sbt:compile (input.hidden-input)
     -1:13.2.0 core:copy (input.hidden-input)
  4x -0:19.3.0 core:close (input.hidden-input)
     -0:06.7.0 sbt:toggle-panel (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
busy-signal 1.4.3 
intentions 1.1.2 
language-scala 1.1.8 
linter 2.2.0 
linter-ui-default 1.6.1 
platformio-ide-terminal 2.5.1 
sbt 0.11.0 
```

**Comment by steelbrain** [comment]
Looks like a bug in the `sbt` package
