### ISSUE TITLE
Uncaught Error: Status 'Refreshing targets for ~/Documents/my/Andurino/Atom-projects/SolarCatcher...

### ISSUE THREAD

**Issue by nezhurayurii** [steelbrain/busy-signal#42]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [busy-signal](https://github.com/steelbrain/busy-signal) package 1.4.3

### Stack Trace

Uncaught Error: Status 'Refreshing targets for /Users/yuriy.nezhura/Documents/my/Andurino/Atom-projects/SolarCatcher,/Users/yuriy.nezhura/Documents/my/Andurino/Atom-projects/Global' is already set

```
At /Users/yuriy.nezhura/.atom/packages/busy-signal/lib/registry.js:50

Error: Status 'Refreshing targets for /Users/yuriy.nezhura/Documents/my/Andurino/Atom-projects/SolarCatcher,/Users/yuriy.nezhura/Documents/my/Andurino/Atom-projects/Global' is already set
    at Registry.statusAdd (/packages/busy-signal/lib/registry.js:50:13)
    at /packages/busy-signal/lib/registry.js:31:12
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Provider.add (/packages/busy-signal/lib/provider.js:21:18)
    at TargetManager.refreshTargets (/packages/build/lib/target-manager.js:57:44)
    at TargetManager.selectActiveTarget (/packages/build/lib/target-manager.js:183:12)
    at /packages/build/lib/target-manager.js:23:82)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:266:23)
    at executeCallback (/packages/tool-bar/lib/tool-bar-button-view.js:106:19)
    at ToolBarButtonView._onClick (/packages/tool-bar/lib/tool-bar-button-view.js:70:7)
```

### Commands

```
     -5:58.3.0 window:focus-next-pane (div.tool-panel.tree-view)
  2x -0:55.8.0 build:select-active-target (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-terminal 0.8.0 
atom-terminal-panel 4.4.4 
autocomplete-clang 0.11.3 
build 0.69.0 
build-platformio 1.2.2 
busy 0.7.0 
busy-signal 1.4.3 
file-icons 2.1.13 
intentions 1.1.5 
language-ini 1.19.0 
linter 2.2.0 
linter-clang 4.1.2 
linter-gcc 0.7.1 
linter-ui-default 1.6.10 
minimap 4.29.7 
platformio-ide 2.0.0-rc.3.1 
platformio-ide-debugger 1.2.4 
platformio-ide-terminal 2.7.0 
tool-bar 1.1.0 
```

**Comment by Arcanemagus** [comment]
This looks like a bug in `build` attempting to set the same status twice.

**Comment by Arcanemagus** [comment]
Closing as this is a bug with `build`.
