### ISSUE TITLE
Uncaught Error: Status 'Generate project symbols' is already set

### ISSUE THREAD

**Issue by lvansnippenburg** [steelbrain/busy-signal#43]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13
**Thrown From**: [busy-signal](https://github.com/steelbrain/busy-signal) package 1.4.3

### Stack Trace

Uncaught Error: Status 'Generate project symbols' is already set

```
At /Users/lvansnippenburg/.atom/packages/busy-signal/lib/registry.js:50

Error: Status 'Generate project symbols' is already set
    at Registry.statusAdd (/packages/busy-signal/lib/registry.js:50:13)
    at /packages/busy-signal/lib/registry.js:31:12
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Provider.add (/packages/busy-signal/lib/provider.js:21:18)
    at TagGenerator.wrapBusySignal (/packages/symbols-view-plus/lib/tag-generator.js:134:16)
    at TagGenerator.generateProjectSymbols (/packages/symbols-view-plus/lib/tag-generator.js:222:17)
    at generateProjectSymbols (/packages/symbols-view-plus/lib/plus/on-file-change-updater.js:32:9)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.destroy (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1509:28)
    at TextBuffer.module.exports.TextBuffer.release (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1556:20)
    at TextEditor.module.exports.TextEditor.destroyed (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:658:25)
    at TextEditor.module.exports.Model.destroy (/Applications/Atom.app/Contents/Resources/app/src/model.js:31:64)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:708:24)
    at TabBarView.module.exports.TabBarView.closeTab (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:341:32)
    at HTMLDivElement.TabView.didClickCloseIcon (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:229:25)
```

### Commands

```
     -9:45.8.0 editor:newline (input.hidden-input)
     -9:44.3.0 core:undo (input.hidden-input)
  3x -9:43.2.0 core:backspace (input.hidden-input)
     -9:29.5.0 core:save (input.hidden-input)
     -8:25.3.0 core:copy (input.hidden-input)
     -7:52.5.0 core:confirm (input.hidden-input)
     -7:43.4.0 editor:newline (input.hidden-input)
     -7:42.8.0 core:paste (input.hidden-input)
     -7:42 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-live-server 2.2.0 
atom-minify 0.8.0 
autocomplete-html-entities 0.2.0 
autocomplete-json 5.5.0 
autocomplete-php 0.3.7 
bracket-matcher-highlight 0.5.0 
busy-signal 1.4.3 
docker 0.8.0 
file-icons 2.1.13 
highlight-selected 0.13.1 
intentions 1.1.5 
language-docker 1.1.8 
language-vue 0.23.1 
language-vue-component 0.5.0 
linter 2.2.0 
linter-docker 0.2.1 
linter-ui-default 1.6.10 
php-integrator-autocomplete-plus 1.6.1 
php-server 0.8.0 
platformio-ide-terminal 2.7.0 
remote-sync-pro 5.1.1 
symbols-list 2.4.1 
symbols-tree-view 0.14.0 
symbols-view-plus 0.117.0-plus.1 
tree-view-git-status 1.4.0 
vue2-autocomplete 0.1.0-alpha.4 
```

**Comment by jonyeezs** [comment]
I get the same error but for a different pkg that's utilizing busy-signal.

Problem is when i try to trigger the same command twice.

This should be handled gracefully rather than throwing an error exception

**Comment by Arcanemagus** [comment]
@jonyeezs You should file this on the package using `busy-signal`. They either need to use a different status (far more likely scenario), or not tell `busy-signal` about the same thing twice.

**Comment by jonyeezs** [comment]
Make sense. Thanks.

**Comment by Arcanemagus** [comment]
To provide a bit more context this is _purposely_ thrown as an error, because there is no situation where this is correct. I'm closing this issue as it's a bug in the user of `busy-signal`, nothing wrong with this package.
