### ISSUE TITLE
Uncaught Error: Status 'Refreshing targets for ~/git/tools_scripts_dotfiles/example_packages/db_m...

### ISSUE THREAD

**Issue by gocarlos** [steelbrain/busy-signal#44]
[Enter steps to reproduce:]

1. ctrl + alt + b
2. ...

**Atom**: 1.24.0-beta1 x64
**Electron**: 1.6.15
**OS**: Ubuntu Bionic
**Thrown From**: [busy-signal](https://github.com/steelbrain/busy-signal) package 1.4.3

### Stack Trace

Uncaught Error: Status 'Refreshing targets for /home/gocarlos/git/tools_scripts_dotfiles/example_packages/db_manager' is already set

```
At /home/gocarlos/.atom/packages/busy-signal/lib/registry.js:50

Error: Status 'Refreshing targets for /home/gocarlos/git/tools_scripts_dotfiles/example_packages/db_manager' is already set
    at Registry.statusAdd (/packages/busy-signal/lib/registry.js:50:13)
    at /packages/busy-signal/lib/registry.js:31:12
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Provider.add (/packages/busy-signal/lib/provider.js:21:18)
    at TargetManager.refreshTargets (/packages/build/lib/target-manager.js:57:44)
    at TargetManager.getTargets (/packages/build/lib/target-manager.js:220:19)
    at Object.startNewBuild (/packages/build/lib/build.js:111:40)
    at /packages/build/lib/build.js:270:14
    at saveAndContinue (/packages/build/lib/build.js:277:7)
    at Object.doSaveConfirm (/packages/build/lib/build.js:281:7)
    at Object.build (/packages/build/lib/build.js:264:10)
    at /packages/build/lib/build.js:25:69)
    at CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom-beta/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom-beta/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom-beta/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -2:09.1.0 core:backspace (input.hidden-input)
     -2:08.6.0 core:save (input.hidden-input)
     -2:08.4.0 core:move-up (input.hidden-input)
     -2:08.1.0 editor:newline (input.hidden-input)
     -2:07.8.0 core:save (input.hidden-input)
     -1:13.2.0 editor:toggle-line-comments (input.hidden-input)
  2x -1:12.7.0 core:save (input.hidden-input)
     -0:43.1.0 editor:toggle-line-comments (input.hidden-input)
     -0:43 core:save (input.hidden-input)
     -0:32.6.0 core:delete (input.hidden-input)
  2x -0:32.1.0 core:save (input.hidden-input)
  6x -0:24.7.0 editor:move-to-end-of-word (input.hidden-input)
     -0:23.1.0 editor:select-to-beginning-of-word (input.hidden-input)
  2x -0:17.6.0 core:backspace (input.hidden-input)
  2x -0:16.7.0 core:save (input.hidden-input)
     -0:08.0 build:trigger (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-clang 0.11.4 
build 0.70.0 
build-cmake 0.11.0 
busy-signal 1.4.3 
clang-format 1.30.0 
formatter 2.12.4 
language-cmake 0.3.0 
sync-settings 0.8.3 
```

**Comment by steelbrain** [comment]
Hi @gocarlos 

It would appear the `build` package is setting the same status more than once. Could you please reopen this issue in their repository?

Cheers

**Comment by riazlatib** [comment]
Why am I getting these emails? (riazlatib@gmail.com)

-- 
Riaz Latib

**Comment by Arcanemagus** [comment]
@riazlatib You are watching this repository: [busy-signal Watchers](https://github.com/steelbrain/busy-signal/watchers). If you stop watching the repository you will stop getting notifications for all issues/PRs.
