### ISSUE TITLE
Uncaught Error: Status 'sbt spark-learner: starting sbt' is already set

### ISSUE THREAD

**Issue by Lcafebabe** [steelbrain/busy-signal#50]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: [busy-signal](https://github.com/steelbrain/busy-signal) package 1.4.3

### Stack Trace

Uncaught Error: Status 'sbt spark-learner: starting sbt' is already set

```
At C:\Users\Administrator\.atom\packages\busy-signal\lib\registry.js:50

Error: Status 'sbt spark-learner: starting sbt' is already set
    at Registry.statusAdd (/packages/busy-signal/lib/registry.js:50:13)
    at /packages/busy-signal/lib/registry.js:31:12
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Provider.add (/packages/busy-signal/lib/provider.js:21:18)
    at Project.module.exports.Project.startTerm (/packages/sbt/lib/project.coffee:49:19)
    at /packages/sbt/lib/project.coffee:91:12
    at FSReqWrap.oncomplete (fs.js:114:15)
```

### Commands

```
     -2:10.1.0 core:move-up (input.hidden-input)
  2x -1:39.3.0 core:paste (input.hidden-input)
     -1:35.7.0 core:backspace (input.hidden-input)
  4x -1:35.4.0 core:move-right (input.hidden-input)
     -1:34.6.0 core:backspace (input.hidden-input)
  4x -1:33.8.0 core:move-right (input.hidden-input)
     -1:28.9.0 core:save (input.hidden-input)
     -1:11.5.0 sbt:toggle-panel (input.hidden-input)
     -0:52.8.0 core:confirm (input.hidden-input)
     -0:44.2.0 intentions:highlight (input.hidden-input)
     -0:44.1.0 command-palette:toggle (input.hidden-input)
  2x -0:43.1.0 core:backspace (input.hidden-input)
  7x -0:40.4.0 core:move-down (input.hidden-input)
     -0:37.2.0 core:move-up (input.hidden-input)
     -0:36.6.0 core:confirm (input.hidden-input)
     -0:36.6.0 sbt:toggle-panel (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
intentions 1.1.5 
language-plantuml 0.2.0 
language-scala 1.1.9 
linter 2.2.0 
linter-scalac 1.4.4 
linter-ui-default 1.7.1 
node-debugger 1.10.1 
node-repl 0.5.0 
nodejs-snippets 2.0.2 
plantuml-viewer 0.7.2 
platformio-ide-terminal 2.8.1 
sbt 0.13.0 
script 3.17.3 
teletype 0.12.2 
```

**Comment by Arcanemagus** [comment]
You'll want to file this on the [sbt](https://github.com/inkytonik/atom-sbt) package, it's a violation of the API to attempt to set two statuses with the same key, as this error is saying they attempted to do.
