### ISSUE TITLE
Uncaught Error: Status 'Uploading ~/doc.html to doc.html...' is already set

### ISSUE THREAD

**Issue by leheiz** [steelbrain/busy-signal#59]
1. Install eXist-db package
2. Select eXistdb - Edit Configuration for Project. sync = true
3. Change and save a file in the project
4. busy-signal error appears

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Ubuntu 17.10
**Thrown From**: [busy-signal](https://github.com/steelbrain/busy-signal) package 1.4.3

### Stack Trace

Uncaught Error: Status 'Uploading ~/doc.html to doc.html...' is already set

```
At ~/.atom/packages/busy-signal/lib/registry.js:50

Error: Status 'Uploading ~/doc.html to doc.html...' is already set
    at Registry.statusAdd (/packages/busy-signal/lib/registry.js:50:13)
    at /packages/busy-signal/lib/registry.js:31:12
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Provider.add (/packages/busy-signal/lib/provider.js:21:18)
    at Object.updateStatus (/packages/existdb/lib/existdb.coffee:245:27)
    at /packages/existdb/lib/existdb.coffee:42:42
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Sync.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Sync.store (/packages/existdb/lib/sync.js:69:14)
    at /packages/existdb/lib/sync.js:27:34
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at didChangeCallback (/usr/share/atom/resources/app/src/project.js:381:28)
    at PathWatcher.onNativeEvents (/usr/share/atom/resources/app/src/path-watcher.js:533:13)
    at sub.native.onDidChange.events (/usr/share/atom/resources/app/src/path-watcher.js:436:64)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at NSFWNativeWatcher.onEvents (/usr/share/atom/resources/app/src/path-watcher.js:167:24)
    at handler (/usr/share/atom/resources/app/src/path-watcher.js:276:18)
```

### Commands

```
     -0:20.1.0 intentions:highlight (input.hidden-input)
     -0:19.4.0 core:save (input.hidden-input)
     -0:03.0 intentions:highlight (input.hidden-input)
     -0:02.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
existdb 0.8.0 
hyperclick 0.1.5 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.7.1 
```

**Comment by joewiz** [comment]
Cc: @wolfgangm, creator of https://github.com/eXist-db/atom-existdb.

**Comment by Arcanemagus** [comment]
Please file a bug on that package, this is a problem in their code that is being thrown as an error here because it's invalid usage of the API.
