### ISSUE TITLE
Uncaught Error: Status 'Refreshing targets for C:/les' is already set

### ISSUE THREAD

**Issue by etozecat** [steelbrain/busy-signal#67]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.36.1 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [busy-signal](https://github.com/steelbrain/busy-signal) package 2.0.1

### Stack Trace

Uncaught Error: Status 'Refreshing targets for C:\les' is already set

```
At C:\Users\delfi\.atom\packages\busy-signal\lib\registry.js:53

Error: Status 'Refreshing targets for C:\les' is already set
    at Registry.statusAdd (/packages/busy-signal/lib/registry.js:53:13)
    at /packages/busy-signal/lib/registry.js:31:12
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:1172164)
    at Emitter.emit (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:1173605)
    at Provider.add (/packages/busy-signal/lib/provider.js:23:18)
    at TargetManager.refreshTargets (/packages/build/lib/target-manager.js:57:44)
    at TargetManager.getTargets (/packages/build/lib/target-manager.js:220:19)
    at Object.startNewBuild (/packages/build/lib/build.js:111:40)
    at /packages/build/lib/build.js:270:14
    at saveAndContinue (/packages/build/lib/build.js:277:7)
    at Object.doSaveConfirm (/packages/build/lib/build.js:281:7)
    at Object.build (/packages/build/lib/build.js:264:10)
    at /packages/build/lib/build.js:25:69)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:350065)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:348540)
    at BuildView.build (/packages/build/lib/build-view.js:302:19)
    at /packages/build/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.dispatch (/packages/build/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/packages/build/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  3x -0:09.9.0 build:toggle-panel (div.tool-panel.tree-view)
     -0:05.3.0 build:trigger (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
build 0.70.0 
build-cargo 2.0.0 
build-gradle 0.6.0 
build-make 0.13.0 
busy-signal 2.0.1 
ide-java 0.8.3 
intentions 1.1.5 
linter 2.3.0 
linter-ui-default 1.7.1 
```

**Comment by steelbrain** [comment]
Bug is coming from the `build` package, for setting the status twice.
Please report this bug upstream thanks
