### ISSUE TITLE
Uncaught Error: Status 'Checking composer file for silverstripe modules' is already set

### ISSUE THREAD

**Issue by sunnysideup** [steelbrain/busy-signal#69]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Ubuntu 18.04.2
**Thrown From**: [busy-signal](https://github.com/steelbrain/busy-signal) package 2.0.1

### Stack Trace

Uncaught Error: Status 'Checking composer file for silverstripe modules' is already set

```
At /home/thiemen/.atom/packages/busy-signal/lib/registry.js:53

Error: Status 'Checking composer file for silverstripe modules' is already set
    at Registry.statusAdd (/packages/busy-signal/lib/registry.js:53:13)
    at /packages/busy-signal/lib/registry.js:31:12
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1207528)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1208969)
    at Provider.add (/packages/busy-signal/lib/provider.js:23:18)
    at /packages/atom-silverstripe/lib/main.js:31:26
```

### Commands

```
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-silverstripe 3.7.3 
atom-updater-linux 1.3.0 
autoclose-html 0.23.0 
autocomplete-php 0.3.7 
busy-signal 2.0.1 
cssbeautify 1.3.0 
docblockr 0.13.7 
duplicate-line-or-selection 0.9.0 
editorconfig 2.5.0 
ide-vue 0.1.9 
intentions 1.1.5 
language-vue 0.24.0 
linter 2.3.0 
linter-php 1.6.1 
linter-ui-default 1.7.1 
php-cs-fixer 4.1.1 
xml-formatter 0.13.0 
```

**Comment by Arcanemagus** [comment]
Please file this on the [`atom-silverstripe` package](https://github.com/gorriecoe/atom-silverstripe/issues): they are attempting to add the same status more than once, which isn't allowed by the API. If you want this to get fixed please file an issue over there.
