### ISSUE TITLE
Uncaught Error: Status 'Refreshing targets for ~/Documents/2600/Boulder-Dash-1-BBG' is already set

### ISSUE THREAD

**Issue by andrew-davie** [steelbrain/busy-signal#70]
[Enter steps to reproduce:]

1. ...switch project using project-manager
2. ...build project - error thrown

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [busy-signal](https://github.com/steelbrain/busy-signal) package 2.0.1

### Stack Trace

Uncaught Error: Status 'Refreshing targets for /Users/boo/Documents/2600/Boulder-Dash-1-BBG' is already set

```
At /Users/boo/.atom/packages/busy-signal/lib/registry.js:53

Error: Status 'Refreshing targets for /Users/boo/Documents/2600/Boulder-Dash-1-BBG' is already set
    at Registry.statusAdd (/packages/busy-signal/lib/registry.js:53:13)
    at /packages/busy-signal/lib/registry.js:31:12
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1210649)
    at Provider.add (/packages/busy-signal/lib/provider.js:23:18)
    at TargetManager.refreshTargets (/packages/build/lib/target-manager.js:57:44)
    at TargetManager.getTargets (/packages/build/lib/target-manager.js:220:19)
    at Object.startNewBuild (/packages/build/lib/build.js:111:40)
    at /packages/build/lib/build.js:270:14
    at saveAndContinue (/packages/build/lib/build.js:277:7)
    at Object.doSaveConfirm (/packages/build/lib/build.js:281:7)
    at Object.build (/packages/build/lib/build.js:264:10)
    at /packages/build/lib/build.js:25:69)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349123)
    at KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1249835)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1245969)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:284329)
```

### Commands

```
     -0:22.3.0 build:trigger (input.hidden-input)
```

### Non-Core Packages

```
auto-run 0.2.1 
build 0.70.0 
build-make 0.13.0 
busy-signal 2.0.1 
env-from-shell 0.3.0 
language-65asm 10.1.0 
project-manager 3.3.7 
```

**Comment by andrew-davie** [comment]
I see that this is a duplicate, and that this needs to be reported against the build package.
