### ISSUE TITLE
Uncaught Error: Status 'Refreshing targets for ~/StudioProjects/myproject' is already set

### ISSUE THREAD

**Issue by raquezha** [steelbrain/busy-signal#76]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.3
**Thrown From**: [busy-signal](https://github.com/steelbrain/busy-signal) package 2.0.1

### Stack Trace

Uncaught Error: Status 'Refreshing targets for /Users/raquezha/StudioProjects/myproject' is already set

```
At /Users/raquezha/.atom/packages/busy-signal/lib/registry.js:53

Error: Status 'Refreshing targets for /Users/raquezha/StudioProjects/myproject' is already set
    at Registry.statusAdd (/packages/busy-signal/lib/registry.js:53:13)
    at /packages/busy-signal/lib/registry.js:31:12
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1212986)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1214427)
    at Provider.add (/packages/busy-signal/lib/provider.js:23:18)
    at TargetManager.refreshTargets (/packages/build/lib/target-manager.js:57:44)
    at GradleBuildProvider.emit (events.js:182:13)
    at /packages/build-gradle/lib/gradle.js:74:16)
    at FSWatcher.emit (events.js:182:13)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:130:12)
```

### Commands

```
```

### Non-Core Packages

```
android 0.1.0 
atom-clock 0.1.17 
build 0.70.0 
build-gradle 0.6.0 
busy-signal 2.0.1 
file-icons 2.1.39 
git-time-machine 2.1.0 
gradle-ci 1.1.4 
ide-java 0.9.0 
ide-kotlin 0.5.0 
intentions 1.1.5 
language-gradle 0.1.0 
language-groovy 0.7.0 
language-kotlin 0.5.0 
linter 2.3.1 
linter-kotlin 0.6.0 
linter-ktlint 0.2.0 
linter-ui-default 1.8.1 
pigments 0.40.2 
platformio-ide-terminal 2.10.0 
trailing-spaces 0.4.0 
zentabs 0.8.9 
```

**Comment by steelbrain** [comment]
This error is the result of the `build ` package setting the same status twice, please report this upstream!

Thank you
