### ISSUE TITLE
Uncaught Error: Status 'Refreshing targets for ~/Documents\PlatformIO' is already set

### ISSUE THREAD

**Issue by HiTec-Tenshi** [steelbrain/busy-signal#77]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: DESKTOP-F41E0LO
**Thrown From**: [busy-signal](https://github.com/steelbrain/busy-signal) package 2.0.1

### Stack Trace

Uncaught Error: Status 'Refreshing targets for C:\Users\HiTec-Tenshi\Documents\PlatformIO' is already set

```
At C:\Users\HiTec-Tenshi\.atom\packages\busy-signal\lib\registry.js:53

Error: Status 'Refreshing targets for C:\Users\HiTec-Tenshi\Documents\PlatformIO' is already set
    at Registry.statusAdd (/packages/busy-signal/lib/registry.js:53:13)
    at /packages/busy-signal/lib/registry.js:31:12
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:1214120)
    at Emitter.emit (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:1215561)
    at Provider.add (/packages/busy-signal/lib/provider.js:23:18)
    at TargetManager.refreshTargets (/packages/build/lib/target-manager.js:57:44)
    at TargetManager.getTargets (/packages/build/lib/target-manager.js:220:19)
    at Object.startNewBuild (/packages/build/lib/build.js:111:40)
    at /packages/build/lib/build.js:270:14
    at saveAndContinue (/packages/build/lib/build.js:277:7)
    at Object.doSaveConfirm (/packages/build/lib/build.js:281:7)
    at Object.build (/packages/build/lib/build.js:264:10)
    at /packages/build/lib/build.js:64:62)
    at TargetManager.emit (events.js:182:13)
    at /packages/build/lib/target-manager.js:114:127)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:349290)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:347765)
    at Object.runAtomCommand (/packages/platformio-ide/lib/utils.js:52:24)
    at /packages/platformio-ide/lib/main.js:258:30)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:349290)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:347765)
    at ToolBarButtonView.executeCallback (/packages/tool-bar/lib/tool-bar-button-view.js:153:23)
    at ToolBarButtonView._onClick (/packages/tool-bar/lib/tool-bar-button-view.js:127:12)
```

### Commands

```
     -6:40.8.0 platformio-ide:target:upload (input.hidden-input)
     -6:34.3.0 application:show-settings (input.hidden-input)
     -5:37.5.0 platformio-ide:home (div.package-detail)
  5x -4:38.4.0 platformio-ide:target:upload (div.tool-panel.tree-view)
     -1:33 platformio-ide:home (div.tool-panel.tree-view)
     -1:18.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-atom-dark-ui)
     -1:05.9.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
  2x -1:05.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-atom-dark-ui)
     -0:16.7.0 platformio-ide:target:upload (div.tool-panel.tree-view)
     -0:16.7.0 platformio-ide:target:upload-C:\Users\HiTec-Tenshi\Documents\PlatformIO\Projects\WebServer (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-atom-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-python-run 0.9.7 
autocomplete-clang 0.13.0 
autocomplete-html-entities 0.2.0 
build 0.70.0 
build-python 0.12.1 
busy-signal 2.0.1 
docblockr 0.13.7 
file-icons 2.1.39 
gpp-compiler 3.0.7 
highlight-line 0.12.0 
html-head-snippets 0.2.0 
html-includes 0.3.0 
html-tab 1.0.2 
html-tag-auto-complete 0.1.1 
html-to-css 0.2.2 
Hydrogen 2.14.0 
ide-html 0.6.0 
ide-json 0.2.1 
ide-python 1.5.0 
intentions 1.1.5 
language-arduino 0.4.3 
language-ini 1.23.0 
linter 2.3.1 
linter-gcc 0.9.0 
linter-gcc2 0.8.8 
linter-ui-default 1.8.1 
platformio-ide 2.6.0 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.10.0 
python-debugger 0.2.0 
python-indent 1.2.5 
python-tools 0.6.9 
script 3.25.0 
set-syntax 0.4.0 
tool-bar 1.2.2 
```

**Comment by steelbrain** [comment]
This error is the result of the `build ` package setting the same status twice, please report this upstream!

Thank you
