### ISSUE TITLE
Uncaught Error: Status 'sbt example: starting sbt' is already set

### ISSUE THREAD

**Issue by rjczanik** [steelbrain/busy-signal#78]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu Focal
**Thrown From**: [busy-signal](https://github.com/steelbrain/busy-signal) package 2.0.1

### Stack Trace

Uncaught Error: Status 'sbt example: starting sbt' is already set

```
At /home/robert/.atom/packages/busy-signal/lib/registry.js:53

Error: Status 'sbt example: starting sbt' is already set
    at Registry.statusAdd (/packages/busy-signal/lib/registry.js:53:13)
    at /packages/busy-signal/lib/registry.js:31:12
    at Function.simpleDispatch (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:11:1214120)
    at Emitter.emit (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:11:1215561)
    at Provider.add (/packages/busy-signal/lib/provider.js:23:18)
    at Project.module.exports.Project.startTerm (/packages/sbt/lib/project.coffee:49:19)
    at /packages/sbt/lib/project.coffee:91:12
    at FSReqWrap.oncomplete (fs.js:141:20)
```

### Commands

```
     -9:53.6.0 debugger:show-attach-dialog (button.github-StatusBarTile.inline-block)
     -9:51 core:cancel (atom-workspace.workspace.scrollbars-visible-always.theme-dracula-syntax.theme-dracula-ui)
     -9:44 debugger:restart-debugging (input.hidden-input)
     -9:27.9.0 sbt:toggle-panel (input.hidden-input)
     -5:56.4.0 sbt:compile (input.hidden-input)
     -3:04.8.0 sbt:toggle-panel (input.hidden-input)
     -2:52.1.0 sbt:exit (input.hidden-input)
 27x -2:24.9.0 core:backspace (input.hidden-input)
     -2:22.2.0 core:paste (input.hidden-input)
     -2:13.3.0 core:confirm (div.package-detail)
     -1:55.4.0 sbt:exit (input.hidden-input)
     -0:03.6.0 sbt:run (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-sbt-client 0.2.0 
build-sbt 0.6.0 
busy-signal 2.0.1 
count-dracula-syntax 0.1.0 
dracula-syntax 2.0.7 
dracula-ui 0.6.0 
Hydrogen 2.14.1 
hydrogen-launcher 1.2.2 
hydrogen-python 0.0.8 
hydrogen-xdbg 0.0.4 
ide-scala 0.11.0 
language-scala 1.1.10 
linter 2.3.1 
platformio-ide-terminal 2.10.0 
sbt 0.13.0 
```

**Comment by steelbrain** [comment]
This error is the result of the `sbt ` package setting the same status twice, please report this upstream!

Thank you
