### ISSUE TITLE
Uncaught Error: Status 'Refreshing targets for ~/Desktop\python_work' is already set

### ISSUE THREAD

**Issue by Hunter-D86** [steelbrain/busy-signal#79]
[Enter steps to reproduce:]

1. Build Current Project
2. ...

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [busy-signal](https://github.com/steelbrain/busy-signal) package 2.0.1

### Stack Trace

Uncaught Error: Status 'Refreshing targets for C:\Users\hunte\Desktop\python_work' is already set

```
At C:\Users\hunte\.atom\packages\busy-signal\lib\registry.js:53

Error: Status 'Refreshing targets for C:\Users\hunte\Desktop\python_work' is already set
    at Registry.statusAdd (/packages/busy-signal/lib/registry.js:53:13)
    at /packages/busy-signal/lib/registry.js:31:12
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:1201500)
    at Emitter.emit (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:1202941)
    at Provider.add (/packages/busy-signal/lib/provider.js:23:18)
    at TargetManager.refreshTargets (/packages/build/lib/target-manager.js:57:44)
    at TargetManager.getTargets (/packages/build/lib/target-manager.js:220:19)
    at Object.startNewBuild (/packages/build/lib/build.js:111:40)
    at /packages/build/lib/build.js:270:14
    at saveAndContinue (/packages/build/lib/build.js:277:7)
    at Object.doSaveConfirm (/packages/build/lib/build.js:281:7)
    at Object.build (/packages/build/lib/build.js:264:10)
    at /packages/build/lib/build.js:25:69)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:349781)
    at KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:1242286)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:1238420)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:284830)
```

### Commands

```
  3x -7:51.4.0 editor:select-line (input.hidden-input)
     -7:41.6.0 application:open-file (input.hidden-input)
     -6:34.7.0 encoding-selector:show (div.highlights)
     -0:28.1.0 build:trigger (input.hidden-input)
```

### Non-Core Packages

```
build 0.70.0 
build-python 0.12.1 
busy-signal 2.0.1 
```

**Comment by steelbrain** [comment]
This error is the result of the `build` package setting the same status twice, please report this upstream!

Thank you
