### ISSUE TITLE
Uncaught Error: Status 'Refreshing targets for ~/Desktop\Progamming Languages\cpp\Cpp Project\C  ...

### ISSUE THREAD

**Issue by Diohicham** [steelbrain/busy-signal#80]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [busy-signal](https://github.com/steelbrain/busy-signal) package 2.0.1

### Stack Trace

Uncaught Error: Status 'Refreshing targets for C:\Users\hdiou\Desktop\Progamming Languages\cpp\Cpp Project\C  Projects\mA_ke_File_mini' is already set

```
At C:\Users\hdiou\.atom\packages\busy-signal\lib\registry.js:53

Error: Status 'Refreshing targets for C:\Users\hdiou\Desktop\Progamming Languages\cpp\Cpp Project\C  Projects\mA_ke_File_mini' is already set
    at Registry.statusAdd (/packages/busy-signal/lib/registry.js:53:13)
    at /packages/busy-signal/lib/registry.js:31:12
    at Function.simpleDispatch (/app.asar/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/app.asar/node_modules/event-kit/dist/emitter.js:257:28)
    at Provider.add (/packages/busy-signal/lib/provider.js:23:18)
    at TargetManager.refreshTargets (/packages/build/lib/target-manager.js:57:44)
    at CustomFile.emit (events.js:194:13)
    at /packages/build/lib/atom-build.js:84:89)
    at FSWatcher.emit (events.js:194:13)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:131:12)
```

### Commands

```
```

### Non-Core Packages

```
build 0.70.0 
build-make 0.13.0 
busy-signal 2.0.1 
gitlab-integration 0.4.8 
gpp-compiler 3.0.7 
```

**Comment by steelbrain** [comment]
This error is the result of the `build` package setting the same status twice, please report this upstream!

Thank you
